services:
  - type: web
    name: content-hub-os
    env: python
    runtime: python-3.13.0
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
